version: "3"
services:
  # Database
  pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - devops-net
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
  
  # Webservice
  app:
    container_name: devops-app
    build: .
    restart: always
    environment:
      DATABASE_HOST: pgsql
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: test
    ports:
      - "8081:3000"
    networks:
      - devops-net
    depends_on:
      - pgsql

# Red privada para los contenedores
networks:
  devops-net:
    driver: bridge
